# Generated by Django 6.0.3 on 2026-03-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nhập thể loại sách (ví dụ: CNTT, Văn học...)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên sách')),
                ('author', models.CharField(max_length=200, verbose_name='Tác giả')),
                ('summary', models.TextField(help_text='Mô tả nội dung sách', max_length=1000)),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('genre', models.ManyToManyField(help_text='Chọn thể loại cho sách', to='catalog.genre')),
            ],
        ),
    ]
