# Generated by Django 6.0.3 on 2026-03-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_created_at_book_image_book_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tóm tắt nội dung'),
        ),
    ]
