# Generated by Django 6.0.3 on 2026-03-30 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0003_alter_book_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày mượn')),
                ('due_date', models.DateTimeField(verbose_name='Hạn Trả')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày thực tế trả')),
                ('status', models.CharField(choices=[('BORROWED', 'Đang mượn'), ('RETURNED', 'Đã trả'), ('OVERDUE', 'Quá hạn')], default='BORROWED', max_length=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
